### ISSUE TITLE
firebase 

### ISSUE THREAD

**Issue by Moh-AbuArra** [MOSDEV82/fcmhelper#2]
im getting error with your class .. error with httpclient ... can you please share a sample on how to use the class

**Comment by MOSDEV82** [comment]
Hint, you need the GSON and APACHE HTTPCLIENT libraries. I use the following from maven:

    com.google.code.gson:gson:2.72
    org.apache.httpcomponents:httpclient:4.5.22

**Comment by akshay-sarkar** [comment]
httpcore-4.4.6.jar also required in case you are making a basic web service.
